# Logging parameters
logging:
  # Name which which the run will be logged
  run_name: "02_breakout"
  # Comments on the run
  comments: ""

  # Directory where main results are saved
  output_root: "evaluation_results"

# Common parameters for both datasets
data:
  # Size at which to perform the evaluation
  target_input_size: [160, 208]
  # Number of distinct actions present in the dataset
  actions_count: 3
  # True if ground truth annotations are available
  ground_truth_available: False

# Reference dataset parameters
reference_data:
  # Dataset path
  data_root: "data/breakout_v2_160_ours/test"
  # Crop to apply to each frame [left_index, upper_index, right_index, lower_index]
  crop: [0, 0, 160, 208]

# Reference dataset parameters
generated_data:
  # Dataset path
  data_root: "results/02_breakout/evaluation_dataset"
  # Crop to apply to each frame [left_index, upper_index, right_index, lower_index]
  crop: [0, 0, 160, 208]

# Parameters for evaluation
evaluation:

  evaluator: "evaluation.dataset_evaluator_breakout"

  # Parameters for batch building
  batching:
    batch_size: 1
    # Number of observations that each batch sample possesses
    observations_count: 32
    # Number of frames to skip between each observation
    skip_frames: 0
    # Total number of frames that compose an observation
    observation_stacking: 1
    # Number of threads to use for dataloading
    num_workers: 8
